---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/crimes":
    get:
      summary: list crimes
      responses:
        '200':
          description: successful
  "/crimes/download":
    get:
      summary: download crime
      responses:
        '200':
          description: successful
  "/crimes/robberies":
    get:
      summary: robberies crime
      responses:
        '200':
          description: successful
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
